Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -86,36 +86,30 @@ jobs:
       - name: Build Node.js Assets
         run: npm run build
 
+      - name: Introduce Failure
+        run: exit 1  # This command will always fail
+
       - name: Run Tests
         run: ./vendor/bin/phpunit
+        if: ${{ always() }}  # Ensure this step runs even if the previous step fails
 
-  notify_success:
-    name: Telegram Notification on Success
+  notify:
+    name: Telegram Notification
     runs-on: ubuntu-latest
     needs: 
       - laravel_build
       - laravel_test
 
-    if: ${{ needs.laravel_build.result == 'success' && needs.laravel_test.result == 'success' }}
-
     steps:
-      - name: Send Telegram Notification
+      - name: Send Telegram Notification on Success
+        if: ${{ needs.laravel_build.result == 'success' && needs.laravel_test.result == 'success' }}
         uses: appleboy/telegram-action@master
         with:
           to: ${{ secrets.TELEGRAM_CHAT_ID }}
           token: ${{ secrets.TELEGRAM_TOKEN }}
           message: "Proses build dan test Laravel berhasil!"
 
-  notify_failure:
-    name: Telegram Notification on Failure
-    runs-on: ubuntu-latest
-    needs: 
-      - laravel_build
-      - laravel_test
-
-    if: ${{ needs.laravel_build.result == 'failure' || needs.laravel_test.result == 'failure' }}
-
-    steps:
-      - name: Send Telegram Notification
+      - name: Send Telegram Notification on Failure
+        if: ${{ needs.laravel_build.result == 'failure' || needs.laravel_test.result == 'failure' }}
         run: |
           curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} -d text="Proses build atau test Laravel gagal!"
